# Backend image: FastAPI (src/api/) + the pipeline/analytics/sync scripts
# it shares code with. Not the frontend (see frontend/Dockerfile) and not
# Postgres (the official postgres image, see docker-compose.yml).
FROM python:3.12-slim

# libpq5 is psycopg2-binary's runtime dependency. build-essential is not
# needed -- every requirements.txt package ships a manylinux/musllinux
# wheel for this base image, so nothing compiles from source.
RUN apt-get update && apt-get install -y --no-install-recommends \
        libpq5 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY alembic/ alembic/
COPY alembic.ini .
COPY run_all.py run_analytics.py sync_run_to_db.py ./
COPY data/raw/ data/raw/

# models/*.pkl and data/processed/ are generated by `python run_all.py`,
# not baked into the image -- docker-compose.yml bind-mounts them so
# `docker compose exec api python run_all.py` persists its output on the
# host, the same files a non-Docker run would produce.

COPY docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

EXPOSE 8000
ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
