"""initial schema

Revision ID: 0dfc964e8351
Revises: 
Create Date: 2026-09-29 03:48:42.879604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfc964e8351'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wall_time_seconds', sa.Float(), nullable=False),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('raw_data_path', sa.String(length=512), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('pd_roc_auc', sa.Float(), nullable=False),
    sa.Column('pd_pr_auc', sa.Float(), nullable=False),
    sa.Column('pd_brier_raw', sa.Float(), nullable=False),
    sa.Column('pd_brier_calibrated', sa.Float(), nullable=False),
    sa.Column('ead_mae', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.String(length=64), nullable=False),
    sa.Column('window_months', sa.Integer(), nullable=False),
    sa.Column('n_features', sa.Integer(), nullable=False),
    sa.Column('val_roc_auc', sa.Float(), nullable=False),
    sa.Column('val_pr_auc', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'window_months', name='uq_backtest_window')
    )
    op.create_index(op.f('ix_backtest_results_model_run_id'), 'backtest_results', ['model_run_id'], unique=False)
    op.create_table('fairness_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.String(length=64), nullable=False),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('min_max_approval_ratio', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'segment', name='uq_fairness_segment')
    )
    op.create_index(op.f('ix_fairness_checks_model_run_id'), 'fairness_checks', ['model_run_id'], unique=False)
    op.create_table('portfolio_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.String(length=64), nullable=False),
    sa.Column('policy_name', sa.String(length=64), nullable=False),
    sa.Column('el_budget', sa.Float(), nullable=False),
    sa.Column('ead_budget', sa.Float(), nullable=False),
    sa.Column('pd_increase_max', sa.Float(), nullable=False),
    sa.Column('pd_decrease_min', sa.Float(), nullable=False),
    sa.Column('used_el', sa.Float(), nullable=False),
    sa.Column('used_ead', sa.Float(), nullable=False),
    sa.Column('n_increase_applied', sa.Integer(), nullable=False),
    sa.Column('n_decrease', sa.Integer(), nullable=False),
    sa.Column('n_hold', sa.Integer(), nullable=False),
    sa.Column('total_ep_uplift', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'policy_name', name='uq_portfolio_run_policy')
    )
    op.create_index(op.f('ix_portfolio_runs_model_run_id'), 'portfolio_runs', ['model_run_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('current_limit', sa.Float(), nullable=False),
    sa.Column('recommended_limit', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('pd_current', sa.Float(), nullable=False),
    sa.Column('pd_recommended', sa.Float(), nullable=False),
    sa.Column('ead_current', sa.Float(), nullable=False),
    sa.Column('ead_recommended', sa.Float(), nullable=False),
    sa.Column('ep_current', sa.Float(), nullable=False),
    sa.Column('ep_recommended', sa.Float(), nullable=False),
    sa.Column('ep_uplift', sa.Float(), nullable=False),
    sa.Column('el_uplift_proxy', sa.Float(), nullable=False),
    sa.Column('ead_uplift', sa.Float(), nullable=False),
    sa.Column('top_features', sa.Text(), nullable=True),
    sa.Column('reason_codes', sa.Text(), nullable=True),
    sa.Column('top_shap_value', sa.Float(), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'customer_id', name='uq_recommendation_customer')
    )
    op.create_index('ix_recommendations_action', 'recommendations', ['model_run_id', 'action'], unique=False)
    op.create_index(op.f('ix_recommendations_customer_id'), 'recommendations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recommendations_model_run_id'), 'recommendations', ['model_run_id'], unique=False)
    op.create_table('segment_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.String(length=64), nullable=False),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('segment_value', sa.String(length=32), nullable=False),
    sa.Column('n_customers', sa.Integer(), nullable=False),
    sa.Column('increase_rate', sa.Float(), nullable=False),
    sa.Column('decrease_rate', sa.Float(), nullable=False),
    sa.Column('hold_rate', sa.Float(), nullable=False),
    sa.Column('avg_pd_current', sa.Float(), nullable=False),
    sa.Column('avg_ep_uplift', sa.Float(), nullable=False),
    sa.Column('total_ep_uplift', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'segment', 'segment_value', name='uq_segment_metric')
    )
    op.create_index(op.f('ix_segment_metrics_model_run_id'), 'segment_metrics', ['model_run_id'], unique=False)
    op.create_table('stress_test_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.String(length=64), nullable=False),
    sa.Column('pd_shock', sa.String(length=16), nullable=False),
    sa.Column('n_increase', sa.Integer(), nullable=False),
    sa.Column('n_decrease', sa.Integer(), nullable=False),
    sa.Column('n_hold', sa.Integer(), nullable=False),
    sa.Column('total_ep_uplift', sa.Float(), nullable=False),
    sa.Column('el_used', sa.Float(), nullable=False),
    sa.Column('el_budget_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'pd_shock', name='uq_stress_test_shock')
    )
    op.create_index(op.f('ix_stress_test_results_model_run_id'), 'stress_test_results', ['model_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_test_results_model_run_id'), table_name='stress_test_results')
    op.drop_table('stress_test_results')
    op.drop_index(op.f('ix_segment_metrics_model_run_id'), table_name='segment_metrics')
    op.drop_table('segment_metrics')
    op.drop_index(op.f('ix_recommendations_model_run_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_customer_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_action', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_portfolio_runs_model_run_id'), table_name='portfolio_runs')
    op.drop_table('portfolio_runs')
    op.drop_index(op.f('ix_fairness_checks_model_run_id'), table_name='fairness_checks')
    op.drop_table('fairness_checks')
    op.drop_index(op.f('ix_backtest_results_model_run_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
